#!/usr/bin/env bash
# GENERATED FILE: edit config/exclusions.json and run:
#   python3 tools/check_exclusions.py --write
# Do not edit this file directly.

EXCLUSION_POLICY_NAME=harvest-moon-ipv4-special-purpose
EXCLUSION_POLICY_VERSION=2.0.0
EXCLUSION_POLICY_SOURCE_DATE=2026-07-31
EXCLUSION_POLICY_DIGEST=sha256:d1adfbacca61dd1ee22cc619a8732e1cab2401faada74c68b7dea14655e34193

# Print: CIDR<TAB>rule-id<TAB>rationale<TAB>source.
exclusion_rule_for() {
    local classa=$1
    local classb=$2
    local classc=$3
    local class_c_number=$((classa * 65536 + classb * 256 + classc))

    if (( class_c_number >= 0 && class_c_number <= 65535 )); then
        printf '%s\t%s\t%s\t%s' 0.0.0.0/8 this-network 'This network is not globally routed' 'IANA IPv4 Special-Purpose Address Registry'
        return 0
    fi
    if (( class_c_number >= 655360 && class_c_number <= 720895 )); then
        printf '%s\t%s\t%s\t%s' 10.0.0.0/8 rfc1918-private 'Private-use address space' 'RFC 1918'
        return 0
    fi
    if (( class_c_number >= 6569984 && class_c_number <= 6586367 )); then
        printf '%s\t%s\t%s\t%s' 100.64.0.0/10 shared-address-space 'Shared address space for carrier-grade NAT' 'RFC 6598'
        return 0
    fi
    if (( class_c_number >= 8323072 && class_c_number <= 8388607 )); then
        printf '%s\t%s\t%s\t%s' 127.0.0.0/8 loopback 'Local host loopback space' 'RFC 1122'
        return 0
    fi
    if (( class_c_number >= 11140608 && class_c_number <= 11140863 )); then
        printf '%s\t%s\t%s\t%s' 169.254.0.0/16 link-local 'IPv4 link-local autoconfiguration' 'RFC 3927'
        return 0
    fi
    if (( class_c_number >= 11276288 && class_c_number <= 11280383 )); then
        printf '%s\t%s\t%s\t%s' 172.16.0.0/12 rfc1918-private 'Private-use address space' 'RFC 1918'
        return 0
    fi
    if (( class_c_number >= 12625920 && class_c_number <= 12626175 )); then
        printf '%s\t%s\t%s\t%s' 192.168.0.0/16 rfc1918-private 'Private-use address space' 'RFC 1918'
        return 0
    fi
    if (( class_c_number >= 12582912 && class_c_number <= 12582912 )); then
        printf '%s\t%s\t%s\t%s' 192.0.0.0/24 protocol-assignments 'IETF protocol assignments and infrastructure' 'IANA IPv4 Special-Purpose Address Registry'
        return 0
    fi
    if (( class_c_number >= 12582914 && class_c_number <= 12582914 )); then
        printf '%s\t%s\t%s\t%s' 192.0.2.0/24 documentation-1 'Documentation and examples' 'RFC 5737'
        return 0
    fi
    if (( class_c_number >= 12605539 && class_c_number <= 12605539 )); then
        printf '%s\t%s\t%s\t%s' 192.88.99.0/24 deprecated-6to4-relay-anycast 'Deprecated 6to4 relay anycast space is not globally reachable; conservative whole-/24 exclusion' 'IANA IPv4 Special-Purpose Address Registry; RFC 7526'
        return 0
    fi
    if (( class_c_number >= 12980736 && class_c_number <= 12981247 )); then
        printf '%s\t%s\t%s\t%s' 198.18.0.0/15 benchmarking 'Network interconnect device benchmarking' 'RFC 2544'
        return 0
    fi
    if (( class_c_number >= 12989284 && class_c_number <= 12989284 )); then
        printf '%s\t%s\t%s\t%s' 198.51.100.0/24 documentation-2 'Documentation and examples' 'RFC 5737'
        return 0
    fi
    if (( class_c_number >= 13303921 && class_c_number <= 13303921 )); then
        printf '%s\t%s\t%s\t%s' 203.0.113.0/24 documentation-3 'Documentation and examples' 'RFC 5737'
        return 0
    fi
    if (( class_c_number >= 14680064 && class_c_number <= 15728639 )); then
        printf '%s\t%s\t%s\t%s' 224.0.0.0/4 multicast 'IPv4 multicast space' 'RFC 1112'
        return 0
    fi
    if (( class_c_number >= 15728640 && class_c_number <= 16777215 )); then
        printf '%s\t%s\t%s\t%s' 240.0.0.0/4 reserved-future-use 'Reserved and future-use space' 'RFC 1112; RFC 1812'
        return 0
    fi
    return 0
}
