#!/usr/bin/env python3
"""Generate or verify the executable policy derived from exclusions.json.

The descriptor digest is SHA-256 over UTF-8 JSON encoded with sorted keys and
compact separators after removing the policy_digest member.
"""

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
from pathlib import Path
import shlex
import stat
import sys


ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "config" / "exclusions.json"
SH_PATH = ROOT / "config" / "exclusions.sh"


def canonical_json(document: dict) -> bytes:
    without_digest = dict(document)
    without_digest.pop("policy_digest", None)
    return json.dumps(
        without_digest, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def generated_policy(document: dict) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# GENERATED FILE: edit config/exclusions.json and run:",
        "#   python3 tools/check_exclusions.py --write",
        "# Do not edit this file directly.",
        "",
        f"EXCLUSION_POLICY_NAME={shell_quote(document['policy_name'])}",
        f"EXCLUSION_POLICY_VERSION={shell_quote(document['policy_version'])}",
        f"EXCLUSION_POLICY_SOURCE_DATE={shell_quote(document['source_date'])}",
        f"EXCLUSION_POLICY_DIGEST={shell_quote(document['policy_digest'])}",
        "",
        "# Print: CIDR<TAB>rule-id<TAB>rationale<TAB>source.",
        "exclusion_rule_for() {",
        "    local classa=$1",
        "    local classb=$2",
        "    local classc=$3",
        "    local class_c_number=$((classa * 65536 + classb * 256 + classc))",
        "",
    ]
    for rule in document["rules"]:
        network = ipaddress.ip_network(rule["cidr"], strict=True)
        first_class_c = int(network.network_address) // 256
        last_class_c = int(network.broadcast_address) // 256
        lines.extend(
            [
                f"    if (( class_c_number >= {first_class_c} && class_c_number <= {last_class_c} )); then",
                "        printf '%s\\t%s\\t%s\\t%s' "
                + " ".join(
                    shell_quote(str(rule[key]))
                    for key in ("cidr", "id", "rationale", "source")
                ),
                "        return 0",
                "    fi",
            ]
        )
    lines.extend(["    return 0", "}", ""])
    return "\n".join(lines)


def load() -> dict:
    try:
        document = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cannot read {JSON_PATH}: {exc}")
    if not isinstance(document, dict):
        raise SystemExit("exclusions descriptor must be an object")
    for key in ("policy_name", "policy_version", "source_date", "policy_digest", "rules"):
        if key not in document:
            raise SystemExit(f"descriptor is missing {key}")
    if not isinstance(document["rules"], list) or not document["rules"]:
        raise SystemExit("descriptor rules must be a non-empty array")
    for rule in document["rules"]:
        try:
            network = ipaddress.ip_network(rule["cidr"], strict=True)
            if not isinstance(network, ipaddress.IPv4Network):
                raise ValueError("not IPv4")
            for key in ("id", "rationale", "source"):
                if not isinstance(rule[key], str) or not rule[key]:
                    raise ValueError(f"invalid {key}")
        except (KeyError, ValueError) as exc:
            raise SystemExit(f"invalid policy rule {rule!r}: {exc}")
    return document


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify JSON digest and generated shell")
    parser.add_argument("--write", action="store_true", help="update digest and regenerate exclusions.sh")
    args = parser.parse_args()
    if args.check == args.write:
        parser.error("choose exactly one of --check or --write")

    document = load()
    digest = "sha256:" + hashlib.sha256(canonical_json(document)).hexdigest()
    if args.write:
        document["policy_digest"] = digest
        JSON_PATH.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        SH_PATH.write_text(generated_policy(document), encoding="utf-8")
        SH_PATH.chmod(SH_PATH.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print(f"wrote {JSON_PATH} and {SH_PATH} ({digest})")
        return 0

    failures = []
    if document["policy_digest"] != digest:
        failures.append(f"policy_digest is {document['policy_digest']}, expected {digest}")
    expected_shell = generated_policy(document)
    try:
        actual_shell = SH_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        failures.append(str(exc))
        actual_shell = ""
    if actual_shell != expected_shell:
        failures.append(f"{SH_PATH} is not generated from {JSON_PATH}")
    if not SH_PATH.exists() or not (SH_PATH.stat().st_mode & stat.S_IXUSR):
        failures.append(f"{SH_PATH} is not executable")
    if failures:
        for failure in failures:
            print(f"policy check failed: {failure}", file=sys.stderr)
        return 1
    print(f"policy check passed ({digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
